[package]
name = "ens-core"
version = "0.0.1"
edition = "2021"
rust-version = "1.82"
license = "UNLICENSED"
publish = false
authors = ["LLT TCP team"]

[dependencies]
telio-utils = { git = "https://github.com/NordSecurity/libtelio.git" }
telio-sockets = { git = "https://github.com/NordSecurity/libtelio.git" }
thiserror = "2"
log = { version = "0.4.33", features = ["std"] }

[dev-dependencies]

[lints.clippy]
empty-line-after-doc-comments = "allow"
