[package]
name = "ens-core"
version = "0.0.1"
edition = "2021"
rust-version = "1.82"
license = "UNLICENSED"
publish = false
authors = ["LLT TCP team"]

[dependencies]
telio-utils = { git = "https://github.com/NordSecurity/libtelio.git" }
telio-sockets = { git = "https://github.com/NordSecurity/libtelio.git" }
thiserror = "2"
log = { version = "0.4.33", features = ["std"] }
built = "0.8.0"
parking_lot = "0.12.5"


[lints.clippy]
empty-line-after-doc-comments = "allow"

[build-dependencies]
built = { version = "0.8.0", features = ["chrono", "git2"] }
