[package]
name = "ens-core"
version = "0.0.1"
edition = "2021"
rust-version = "1.82"
license = "UNLICENSED"
publish = false
authors = ["LLT TCP team"]

[dependencies]
telio-utils = { git = "https://github.com/NordSecurity/libtelio.git", rev="e32fbd15ddfccb3a67c34f6bd1240fbd18791f4b" }
telio-sockets = { git = "https://github.com/NordSecurity/libtelio.git", rev="e32fbd15ddfccb3a67c34f6bd1240fbd18791f4b" }
telio-crypto = { git = "https://github.com/NordSecurity/libtelio.git", rev="e32fbd15ddfccb3a67c34f6bd1240fbd18791f4b" }
tokio = { version = "1.53.1", default-features = false, features = ["macros", "rt-multi-thread", "sync", "time"] }
parking_lot = "0.12.5"
llt-proto = { git = "https://github.com/NordSecurity/llt-proto.git", tag = "v2.0.0" }
thiserror = { version = "2", default-features = false }
log = { version = "0.4.34", default-features = false, features = ["std"] }
built = { version = "0.8.0", default-features = false }
rustls = { version = "0.23.45", default-features = false, features = ["aws_lc_rs"] }
tonic = { version = "0.14.5", default-features = false }
http = { version = "1.5.0", default-features = false }
tokio-rustls = { version = "0.26.6", default-features = false }
base64 = { version = "0.23", default-features = false, features = ["alloc"] }
blake3 = { version = "1.8.7", default-features = false }
hyper-util = { version = "0.1.20",  default-features = false, features = ["tokio"] }
uuid = { version = "1.20.0",  default-features = false, features = ["v4"] }
tower = { version = "0.5.3", default-features = false }
sha2 = { version = "0.10.9", default-features = false }
zeroize = { version = "1.8.2",  default-features = false, features = ["zeroize_derive"] }
x25519-dalek = { version = "2.0.1", default-features = false }
crypto_box = { version = "0.9.1", default-features = false }
hex = { version = "0.4.3", default-features = false }
rand = "0.9.5"


[lints.clippy]
empty-line-after-doc-comments = "allow"

[build-dependencies]
built = { version = "0.8.0", features = ["chrono", "git2"] }

[dev-dependencies]
assert_matches = "1.5.0"
bstr = { version = "1.13.1", default-features = false }
ens-stub = { path = "../ens-stub" }
rcgen = { version = "0.14.7", default-features = false, features = ["pem", "aws_lc_rs"]}
rstest = { version = "0.26.1", default-features = false }
test-log = "0.2.21"
tonic = { version = "0.14.6", features = ["tls-aws-lc"] }
telio-utils = { git = "https://github.com/NordSecurity/libtelio.git", rev="e32fbd15ddfccb3a67c34f6bd1240fbd18791f4b", features = ["mockall"]  }

